<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Model Building</title>

<script src="site_libs/header-attrs-2.29/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-6.4.2/css/all.min.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.4.2/css/v4-shims.min.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="report.html">Project Report</a>
</li>
<li>
  <a href="data_description.html">Data Description</a>
</li>
<li>
  <a href="EDA.html">EDA</a>
</li>
<li>
  <a href="model.html">Statistical Analysis</a>
</li>
<li>
  <a href="https://fianltornadoes.shinyapps.io/rshiny/">Shiny App</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    <span class="fa fa-envelope fa-lg"></span>
     
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="mailto:jc6422@cumc.columbia.edu">Jianing Chen</a>
    </li>
    <li>
      <a href="mailto:jw4690@cumc.columbia.edu">Jingxi Wang</a>
    </li>
    <li>
      <a href="mailto:xw3038@cumc.columbia.edu">Xikun Wang</a>
    </li>
    <li>
      <a href="mailto:pz2334@cumc.columbia.edu">Puyuan Zhang</a>
    </li>
    <li>
      <a href="mailto:tz2659@cumc.columbia.edu">Tianci Zhu</a>
    </li>
  </ul>
</li>
<li>
  <a href="https://github.com/jingxw02/p8105_final_tornado">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Model Building</h1>

</div>


<pre class="r"><code>tornado_data &lt;- read.csv(&quot;./data/1950-2023_actual_tornadoes.csv&quot;, na.strings = c(&quot;NA&quot;, &quot;N/A&quot;, &quot; &quot;))

cleaned &lt;- tornado_data |&gt;
  filter(yr &gt;= 2000) |&gt;
  select(-tz, -stf, -ns, -sn, -sg, -f1, -f2, -f3, -f4) |&gt;
  relocate(fc, .after = mag)|&gt;
  drop_na()
  

write.csv(cleaned, &quot;cleaned_df.csv&quot;, row.names = FALSE)</code></pre>
<div
id="what-are-the-key-factors-that-contribute-to-the-number-of-injuries-caused-by-tornadoes"
class="section level2">
<h2>1. What are the key factors that contribute to the number of
injuries caused by tornadoes?</h2>
<div id="pruning" class="section level5">
<h5>1. Pruning</h5>
<pre class="r"><code># Pruning
best_cp &lt;- tree_model$cptable[which.min(tree_model$cptable[, &quot;xerror&quot;]), &quot;CP&quot;]


pruned_tree &lt;- prune(tree_model, cp = best_cp)</code></pre>
</div>
<div id="pruned-tree-model" class="section level3">
<h3>Pruned tree model</h3>
<pre class="r"><code>rpart.plot(pruned_tree, type = 3, extra = 101, fallen.leaves = TRUE)</code></pre>
<p><img src="model_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>The pruned decision tree identifies magnitude (<code>mag</code>) as
the primary factor influencing tornado-related injuries. Tornadoes with
<code>mag</code> &lt; 4 predict minimal injuries, averaging 0.2 injuries
in most cases, indicating that low-magnitude tornadoes pose minimal
risk. For tornadoes with <code>mag</code> &gt;= 4, injuries increase
substantially, with additional splits showing that long paths
(<code>len</code> &gt;= 75 miles) and high property loss
(<code>loss</code> &gt;= 23) are associated with severe injury outcomes.
This hierarchy underscores the dominant role of magnitude, with path
length and property loss acting as secondary risk factors in extreme
scenarios.</p>
<div id="cross-validation" class="section level5">
<h5>2. Cross-Validation</h5>
<pre class="r"><code># Cross-Validation
set.seed(123)
train_control &lt;- trainControl(method = &quot;cv&quot;, number = 10)
cv_model &lt;- train(
  inj ~ mag + wid + len + loss,
  data = cleaned,
  method = &quot;rpart&quot;,
  trControl = train_control,
  tuneLength = 10
)</code></pre>
</div>
</div>
<div id="cross-validated-tree-model" class="section level3">
<h3>Cross-validated tree model</h3>
<pre class="r"><code>rpart.plot(cv_model$finalModel, type = 3, extra = 101, fallen.leaves = TRUE)</code></pre>
<p><img src="model_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>The cross-validated tree confirms that magnitude (<code>mag</code>)
is the most critical factor, with injuries significantly increasing for
<code>mag</code> &gt;= 4. This model captures more nuanced relationships
among variables, such as the interplay between path length
(<code>len</code>) and property loss (<code>loss</code>). Long paths
(<code>len</code> &gt;= 75) consistently predict the highest injury
counts, while shorter paths refine the predictions based on magnitude
and loss. This suggests that while cross-validation slightly improves
predictive accuracy, the variable hierarchy remains consistent with the
pruned tree.</p>
</div>
<div id="importance" class="section level3">
<h3>Importance</h3>
<pre class="r"><code>tree_model$variable.importance</code></pre>
<pre><code>##        mag        len       loss        wid 
## 947829.455 605831.823  63904.583   9161.009</code></pre>
<pre class="r"><code>cv_model$finalModel$variable.importance</code></pre>
<pre><code>##        mag        len       loss        wid 
## 947829.455 605831.823  63904.583   9161.009</code></pre>
<p>Variable importance rankings in both models reinforce the dominance
of magnitude (<code>mag</code>), which has a significantly higher score
than the other variables. Path length (<code>len</code>) is the second
most influential factor, followed by property loss (<code>loss</code>).
Tornado width (<code>wid</code>) has a minor role, suggesting that its
contribution to injury predictions is less direct. These rankings
highlight the importance of focusing on magnitude and path length when
assessing tornado injury risks.</p>
<p>The decision tree visualizations clearly illustrate key thresholds in
the data. For <code>mag</code> &gt;= 4, injuries escalate, particularly
when combined with long paths (<code>len</code> &gt;= 75) or high
property loss (<code>loss</code> &gt;= 23). Tornadoes with
<code>mag</code> &lt; 4 result in minimal injuries regardless of other
variables. These thresholds provide actionable insights for disaster
preparedness, emphasizing the need to monitor and respond aggressively
to high-magnitude and long-path tornadoes.</p>
</div>
</div>
<div
id="how-do-tornado-characteristics-predict-the-occurrence-of-longer-path-tornadoes"
class="section level2">
<h2>2. How do tornado characteristics predict the occurrence of
longer-path tornadoes?</h2>
<pre class="r"><code>library(pROC)
library(caret)

set.seed(123)

cleaned$long_path_binary &lt;- factor(ifelse(cleaned$len &gt; quantile(cleaned$len, 0.75), 1, 0),
                                   levels = c(0, 1), labels = c(&quot;No&quot;, &quot;Yes&quot;))

# Set up Cross-Validation

cv_control &lt;- trainControl(
  method = &quot;cv&quot;,
  number = 10, 
  classProbs = TRUE, 
  summaryFunction = twoClassSummary
)

# Train Logistic Regression Model with Cross-Validation

cv_logistic_model &lt;- train(
  long_path_binary ~ slat + slon + mag * wid,
  data = cleaned,
  method = &quot;glm&quot;,
  family = binomial(),
  metric = &quot;ROC&quot;, 
  trControl = cv_control
)

cv_logistic_model</code></pre>
<pre><code>## Generalized Linear Model 
## 
## 29507 samples
##     4 predictor
##     2 classes: &#39;No&#39;, &#39;Yes&#39; 
## 
## No pre-processing
## Resampling: Cross-Validated (10 fold) 
## Summary of sample sizes: 26556, 26557, 26556, 26557, 26556, 26556, ... 
## Resampling results:
## 
##   ROC       Sens       Spec     
##   0.835001  0.9543641  0.3930859</code></pre>
<p>The cross-validation step evaluates the model’s ability to predict
long-path tornadoes. The 10-fold cross-validation process splits the
data into training and testing subsets to ensure that the model
generalizes well to unseen data. The ROC value of 0.835 indicates that
the model has a good discriminative ability to differentiate between
long-path and short-path tornadoes. This is complemented by high
sensitivity (0.954) showing that most long-path tornadoes are correctly
identified, while specificity (0.393) highlights room for improvement in
minimizing false positives.</p>
<pre class="r"><code>cv_results &lt;- cv_logistic_model$results
cv_results</code></pre>
<pre><code>##   parameter      ROC      Sens      Spec       ROCSD      SensSD     SpecSD
## 1      none 0.835001 0.9543641 0.3930859 0.006624361 0.004754727 0.01020199</code></pre>
<pre class="r"><code>roc_curve &lt;- roc(
  cleaned$long_path_binary,
  predict(cv_logistic_model, newdata = cleaned, type = &quot;prob&quot;)[, &quot;Yes&quot;]
)</code></pre>
<pre><code>## Setting levels: control = No, case = Yes</code></pre>
<pre><code>## Setting direction: controls &lt; cases</code></pre>
<pre class="r"><code>plot(roc_curve, main = &quot;ROC Curve with Cross-Validation&quot;, col = &quot;blue&quot;, lwd = 2)
abline(a = 0, b = 1, lty = 2, col = &quot;gray&quot;)</code></pre>
<p><img src="model_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>The ROC curve visually confirms the model’s performance, with the
curve substantially above the diagonal line (representing random
chance). The area under the curve (AUC = 0.835) further reinforces the
logistic regression’s capability to classify tornado paths effectively.
While sensitivity is strong, specificity should be revisited, perhaps by
balancing the dataset or exploring more feature interactions.</p>
<pre class="r"><code>library(car)

vif(cv_logistic_model$finalModel)</code></pre>
<pre><code>##      slat      slon       mag       wid `mag:wid` 
##  1.045057  1.055685  2.108353  2.683890  4.213116</code></pre>
<pre class="r"><code>summary(cv_logistic_model$finalModel)</code></pre>
<pre><code>## 
## Call:
## NULL
## 
## Coefficients:
##               Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -1.9785554  0.2067003  -9.572  &lt; 2e-16 ***
## slat         0.0120309  0.0033344   3.608 0.000308 ***
## slon         0.0085452  0.0020045   4.263 2.02e-05 ***
## mag          0.7974274  0.0306795  25.992  &lt; 2e-16 ***
## wid          0.0054422  0.0001725  31.556  &lt; 2e-16 ***
## `mag:wid`   -0.0006512  0.0001119  -5.820 5.87e-09 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 33182  on 29506  degrees of freedom
## Residual deviance: 25463  on 29501  degrees of freedom
## AIC: 25475
## 
## Number of Fisher Scoring iterations: 6</code></pre>
<p>The variable importance analysis highlights significant
predictors:</p>
<ul>
<li><p>Magnitude (mag): Tornado magnitude is the strongest predictor,
with higher magnitudes leading to an increased likelihood of long
paths.</p></li>
<li><p>Width (wid): Wider tornadoes significantly contribute to
predicting long-path events, consistent with their destructive
nature.</p></li>
<li><p>Latitude (slat): Tornadoes at higher latitudes tend to have
longer paths.</p></li>
<li><p>Longitude (slon): Tornadoes further east also predict longer
paths.</p></li>
<li><p>Interaction term (mag:wid): Indicates that the combination of
magnitude and width is vital, possibly reflecting compound effects on
destruction.</p></li>
</ul>
<p>The variance inflation factor (VIF) values are all below the commonly
accepted threshold of 5, suggesting no severe multicollinearity among
predictors. This ensures model stability and interpretability.</p>
</div>
<div
id="does-the-distribution-of-tornado-widths-fit-an-exponential-distribution"
class="section level2">
<h2>3. Does the distribution of tornado widths fit an exponential
distribution?</h2>
<pre class="r"><code>library(MASS)
library(ggplot2)

tornado_widths &lt;- cleaned$wid[!is.na(cleaned$wid)]

exp_fit &lt;- fitdistr(tornado_widths, &quot;exponential&quot;)

cat(&quot;MLE Estimated Rate (Lambda):&quot;, exp_fit$estimate, &quot;\n&quot;)</code></pre>
<pre><code>## MLE Estimated Rate (Lambda): 0.007025694</code></pre>
<p>This analysis examines whether tornado widths follow an exponential
distribution by using Maximum Likelihood Estimation (MLE) to estimate
the rate parameter (λ). The estimated rate parameter (λ) is 0.0070,
indicating the rapid decline in the density of larger tornado widths.
The exponential distribution assumes that events (in this case, tornado
widths) decrease in frequency exponentially as their magnitude
increases. This aligns with the expectation that narrower tornadoes are
much more frequent than wider ones.</p>
<pre class="r"><code>ggplot(data.frame(widths = tornado_widths), aes(x = widths)) +
  geom_histogram(aes(y = ..density..), bins = 30, fill = &quot;lightblue&quot;, color = &quot;black&quot;) +
  stat_function(fun = dexp, args = list(rate = exp_fit$estimate), color = &quot;red&quot;, size = 1) +
  labs(
    title = &quot;Tornado Widths and Fitted Exponential Distribution&quot;,
    x = &quot;Tornado Width&quot;,
    y = &quot;Density&quot;
  ) +
  theme_minimal()</code></pre>
<p><img src="model_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>The histogram shows that:</p>
<ul>
<li><p>Small tornado widths dominate: A significant proportion of
tornado widths are concentrated near the lower end of the scale,
consistent with the exponential assumption of a high frequency of small
values.</p></li>
<li><p>Exponential decay: The red curve, representing the fitted
exponential distribution, aligns well with the histogram at the lower
widths. This suggests that the exponential model captures the general
trend in tornado widths for the majority of the data.</p></li>
<li><p>Right-tail deviation: At the extreme right (larger widths), the
histogram shows minor deviations from the exponential curve. This
implies that the exponential distribution might underfit the heavier
tails, as some exceptionally wide tornadoes occur more frequently than
the model predicts.</p></li>
</ul>
</div>
<div id="how-do-fatalities-and-loss-differ-across-seasons"
class="section level2">
<h2>4. How do fatalities and loss differ across seasons</h2>
<p>To investigate whether there are significant differences in
fatalities and injuries across seasons (Winter, Spring, Summer, Fall), a
non-parametric method was used here to compare the medians of loss and
fatalities across different seasons</p>
<div id="hypotheses-kruskal-wallis-test" class="section level3">
<h3>Hypotheses Kruskal-Wallis Test</h3>
<p>To evaluate the seasonal differences in tornado impacts,
Kruskal-Wallis tests were conducted for both loss and fatalities across
seasons. The null hypothesis for each test is that the median values of
loss and fatalities are the same across all seasons, while the
alternative hypothesis states that at least one season has a
significantly different median. Using the cleaned dataset, which
includes the categorical variable <code>season</code> and the continuous
variables <code>loss</code> and <code>fat</code> (fatalities), the test
statistics and p-values were calculated to assess the significance of
these differences at a 0.05 significance level. This approach allows for
a robust comparison of median values across seasons, even with
non-normally distributed data.</p>
<pre class="r"><code>cleaned=cleaned |&gt; 
  mutate(
    # Create season as a factor based on the month
    season = factor(case_when(
      mo %in% c(12, 1, 2) ~ &quot;Winter&quot;,
      mo %in% c(3, 4, 5) ~ &quot;Spring&quot;,
      mo %in% c(6, 7, 8) ~ &quot;Summer&quot;,
      mo %in% c(9, 10, 11) ~ &quot;Fall&quot;
    ), levels = c(&quot;Winter&quot;, &quot;Spring&quot;, &quot;Summer&quot;, &quot;Fall&quot;)),
    # Convert mag to a factor
    mag = as.factor(mag)
  )

# Kruskal-Wallis test for loss across seasons
kruskal_loss=kruskal.test(loss ~ season, data = cleaned)
print(kruskal_loss)</code></pre>
<pre><code>## 
##  Kruskal-Wallis rank sum test
## 
## data:  loss by season
## Kruskal-Wallis chi-squared = 1162.5, df = 3, p-value &lt; 2.2e-16</code></pre>
<pre class="r"><code># test for fatalities across seasons
kruskal_fatalities=kruskal.test(fat~ season, data = cleaned)
print(kruskal_fatalities)</code></pre>
<pre><code>## 
##  Kruskal-Wallis rank sum test
## 
## data:  fat by season
## Kruskal-Wallis chi-squared = 146.92, df = 3, p-value &lt; 2.2e-16</code></pre>
<p>The test result shows significant seasonal variations in both
economic losses and fatalities. For economic losses, the p-value was
less than 0.05, indicating strong evidence to reject the null hypothesis
that losses are evenly distributed across all seasons. Similarly, the
p-value for fatalities was less than 0.05, also providing strong
evidence to reject the null hypothesis and conclude that fatalities vary
significantly across seasons.</p>
<p>To further identify specific seasonal differences, post-hoc test were
then utilized. The Dunn’s test with Bonferroni adjustment was then
conducted</p>
</div>
<div id="post-hoc-test-results-for-loss-across-seasons"
class="section level3">
<h3>Post-hoc Test Results for Loss Across Seasons</h3>
<pre class="r"><code># Post-hoc test for loss across seasons
dunn_loss=dunnTest(loss ~ season, data = cleaned, method = &quot;bonferroni&quot;)
print(dunn_loss)</code></pre>
<pre><code>## Dunn (1964) Kruskal-Wallis multiple comparison</code></pre>
<pre><code>##   p-values adjusted with the Bonferroni method.</code></pre>
<pre><code>##        Comparison          Z       P.unadj         P.adj
## 1   Fall - Spring   6.664038  2.664053e-11  1.598432e-10
## 2   Fall - Summer  20.528670  1.193991e-93  7.163947e-93
## 3 Spring - Summer  19.318850  3.728658e-83  2.237195e-82
## 4   Fall - Winter -12.277059  1.202927e-34  7.217560e-34
## 5 Spring - Winter -20.128608  4.144714e-90  2.486828e-89
## 6 Summer - Winter -31.691891 2.009520e-220 1.205712e-219</code></pre>
<p>In the post-hoc Dunn’s test for median based losses, all pairwise
comparisons between seasons show significant differences as the p values
for them are much smaller than 0.05. And it is exhibited that winter
shows significantly higher. Fall has higher losses compared to spring
and summer, and winter generally experiences the highest median of
losses compared to all other seasons. Given the significant seasonal
trends in losses, it is crucial to focus more on Fall and Winter
tornadoes when addressing economic impacts even if the tornadoes are not
most frequently occurring in these seasons</p>
</div>
<div id="post-hoc-test-results-for-fatalities-across-seasons"
class="section level3">
<h3>Post-hoc Test Results for Fatalities Across Seasons</h3>
<pre class="r"><code># Post-hoc test for injuries across seasons
dunn_fatalities=dunnTest(fat~ season, data = cleaned, method = &quot;bonferroni&quot;)
print(dunn_fatalities)</code></pre>
<pre><code>## Dunn (1964) Kruskal-Wallis multiple comparison</code></pre>
<pre><code>##   p-values adjusted with the Bonferroni method.</code></pre>
<pre><code>##        Comparison           Z      P.unadj        P.adj
## 1   Fall - Spring  -0.5929891 5.531884e-01 1.000000e+00
## 2   Fall - Summer   5.3279154 9.934636e-08 5.960781e-07
## 3 Spring - Summer   7.9963062 1.282073e-15 7.692437e-15
## 4   Fall - Winter  -6.0488587 1.458755e-09 8.752529e-09
## 5 Spring - Winter  -6.5895148 4.412662e-11 2.647597e-10
## 6 Summer - Winter -11.4469857 2.434651e-30 1.460791e-29</code></pre>
<p>Regarding the comparisons of median based fatalities between
different seasons, the adjusted p value shows the statistically
significant differences for all except the fall and spring, indicating
the approximately similar median fatalities between these two seasons.
Based on the observations of other comparisons,winter season shows
relatively higher fatalities compare to other seasons, followed by
summer. Therefore, more preventive measures should be taken during
Summer and Winter to address the heightened risks of fatalities.</p>
</div>
</div>
<div
id="how-does-the-magnitude-of-events-predict-the-distribution-of-fatalities"
class="section level2">
<h2>5. How does the magnitude of events predict the distribution of
fatalities?</h2>
<p>To examine whether there is an association between the variables
<code>mag</code> (magnitude) and <code>fat</code> (fatalities) in the
dataset, a Chi-Square test of independence was performed. The Null
Hypothesis (H0) states that the magnitude of the tornadoes and
fatalities are independent. And the Alternative Hypothesis (H1) states
that there is an association between the magnitude of tornado events and
numbers of fatalities.</p>
<pre class="r"><code>table_data=table(cleaned$mag, cleaned$fat)

# Perform Chi-Square Test
chisq.test(table_data)</code></pre>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  table_data
## X-squared = 25983, df = 162, p-value &lt; 2.2e-16</code></pre>
<p>The result shows that the p-value is far below the standard
significance level (e.g., 0.05), so we reject the null hypothesis,
indicating that there is a statistically significant association between
the magnitude of the event and the number of fatalities. This result
statistically confirms the observations initially identified during the
exploratory data analysis (EDA), where trends suggested that higher
magnitudes are likely to result in more fatalities.</p>
</div>
<div
id="model-comparison-on-predicting-fatalities-based-on-event-characteristics."
class="section level2">
<h2>6. Model comparison on predicting fatalities based on event
characteristics.</h2>
<p>The linear regression model was then developed to analyze the
relationship between fatalities (fat) as the dependent variable and
multiple predictors: magnitude (mag), injuries (inj), loss (loss),
length (len), and width (wid). And diagnostics were conducted to
evaluate the assumptions of linear regression, including linearity,
normality, homogeneity of variance, and outliers. The
<code>check_model()</code> function was used to evaluate four
assumptions of linear regression model: Linearity, Normality (QQ Plot),
Homogeneity of Variance (Homoscedasticity) and Influential
Observations</p>
<pre class="r"><code># Prepare the model specification
lm_spec =linear_reg()|&gt;
  set_mode(&quot;regression&quot;)|&gt;
  set_engine(&quot;lm&quot;)

final_model=lm(fat ~ mag + inj + loss + len + wid, data = cleaned)

check_model(final_model, check = c(&quot;linearity&quot;, &quot;qq&quot;, &quot;homogeneity&quot;, &quot;outliers&quot;))</code></pre>
<p><img src="model_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<div id="diagnostic-report-for-linear-regression-model"
class="section level3">
<h3>Diagnostic Report for Linear Regression Model</h3>
<ol style="list-style-type: decimal">
<li><strong>Linearity</strong>: The residuals display a curved pattern,
and the residuals do not scatter randomly around the horizontal line at
zero, indicating that the assumption of linearity is violated.</li>
<li><strong>Homoscedasticity</strong>: the variance of errors is not
constant across all levels of fitted values, so it is also violated</li>
<li><strong>Influential Observations</strong>: Several points,
particularly those with leverage values exceeding 0.2, are flagged as
potentially influential, which requires the further investigation.</li>
<li><strong>Normality check</strong>: The QQ plot demonstrates
significant deviations from normality at both ends.</li>
</ol>
</div>
<div id="polynomial-regression" class="section level3">
<h3>Polynomial Regression</h3>
<p>With the diagnostic observations from the linear regression model, a
more flexible modeling approach was implemented using polynomial terms
and interaction effects to better capture the nonlinear relationships
and reduce the influence of heteroscedasticity and non linearity.</p>
<p>Model 1 was selected with the following predictors as some of them
were tested and observed in the previous analysis:</p>
<ul>
<li>Formula:
<code>fat ~ poly(mag, 2) + poly(inj, 2) + poly(loss, 2) + poly(len, 2) + poly(wid, 2)</code>,
second-order polynomial terms for all predictors (mag, inj, loss, len,
and wid) without interaction terms.</li>
</ul>
<pre class="r"><code># Fit the regression model
model=lm(fat ~ poly(mag, 2) + poly(inj, 2) + poly(loss, 2) + poly(len, 2) + poly(wid, 2), data = cleaned)

# Tidy the model results and print in a neat table
broom::tidy(model) |&gt; 
  knitr::kable(digits = 3, caption = &quot;Regression Model Results with Polynomial Terms&quot;)</code></pre>
<table>
<caption>Regression Model Results with Polynomial Terms</caption>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">0.060</td>
<td align="right">0.004</td>
<td align="right">13.334</td>
<td align="right">0.000</td>
</tr>
<tr class="even">
<td align="left">poly(mag, 2)1</td>
<td align="right">8.860</td>
<td align="right">1.052</td>
<td align="right">8.422</td>
<td align="right">0.000</td>
</tr>
<tr class="odd">
<td align="left">poly(mag, 2)2</td>
<td align="right">15.400</td>
<td align="right">0.855</td>
<td align="right">18.015</td>
<td align="right">0.000</td>
</tr>
<tr class="even">
<td align="left">poly(inj, 2)1</td>
<td align="right">161.696</td>
<td align="right">0.858</td>
<td align="right">188.433</td>
<td align="right">0.000</td>
</tr>
<tr class="odd">
<td align="left">poly(inj, 2)2</td>
<td align="right">-2.946</td>
<td align="right">0.858</td>
<td align="right">-3.435</td>
<td align="right">0.001</td>
</tr>
<tr class="even">
<td align="left">poly(loss, 2)1</td>
<td align="right">-11.555</td>
<td align="right">0.780</td>
<td align="right">-14.815</td>
<td align="right">0.000</td>
</tr>
<tr class="odd">
<td align="left">poly(loss, 2)2</td>
<td align="right">3.483</td>
<td align="right">0.775</td>
<td align="right">4.495</td>
<td align="right">0.000</td>
</tr>
<tr class="even">
<td align="left">poly(len, 2)1</td>
<td align="right">8.696</td>
<td align="right">1.028</td>
<td align="right">8.462</td>
<td align="right">0.000</td>
</tr>
<tr class="odd">
<td align="left">poly(len, 2)2</td>
<td align="right">27.108</td>
<td align="right">0.857</td>
<td align="right">31.628</td>
<td align="right">0.000</td>
</tr>
<tr class="even">
<td align="left">poly(wid, 2)1</td>
<td align="right">1.812</td>
<td align="right">1.029</td>
<td align="right">1.760</td>
<td align="right">0.078</td>
</tr>
<tr class="odd">
<td align="left">poly(wid, 2)2</td>
<td align="right">-1.252</td>
<td align="right">0.827</td>
<td align="right">-1.515</td>
<td align="right">0.130</td>
</tr>
</tbody>
</table>
<p>The comparison model was used to test if simplifying the model by
using fewer polynomial terms and focusing on interactions can improve
generalization and further improve the performance of the prediction. So
Model 2:</p>
<ul>
<li>Formula:
<code>fat ~  poly(mag, 2) + inj:loss + poly(len, 2) + poly(wid, 2)</code>,
second-order polynomial terms for mag, len, and wid, as well as an
interaction term between <code>inj</code> and <code>loss</code>.</li>
</ul>
</div>
<div id="cross-validation-1" class="section level3">
<h3>Cross Validation</h3>
<p>The dataset was split into training and testing sets for
cross-validation, with each model trained on the training set and
evaluated on the corresponding test set. Prediction accuracy was
assessed using the Root Mean Squared Error (RMSE). And the violin plot
is used to visualize the rmse of using cross-validation</p>
<pre class="r"><code>cv_df &lt;- crossv_mc(cleaned, 100) |&gt; 
  mutate(
    # Convert train and test sets to tibbles
    train = map(train, as_tibble),
    test = map(test, as_tibble)
  )</code></pre>
<pre class="r"><code># Fit models and calculate metrics
cv_results=cv_df |&gt; 
  mutate(
    # Fit models with polynomial terms
     model1_mod = map(train, \(df) lm(fat ~ poly(mag, 2) + poly(inj, 2) + poly(loss, 2) + poly(len, 2) + poly(wid, 2), data = df)),
    model2_mod = map(train, \(df) lm(fat ~ poly(mag, 2) + inj:loss + poly(len, 2) + poly(wid, 2), data = df)),
   
  ) |&gt;
  mutate(
    # Calculate RMSE for each model on the test sets
    rmse_model1 = map2_dbl(model1_mod, test, \(mod, df) rmse(model = mod, data = df)),
    rmse_model2 = map2_dbl(model2_mod, test, \(mod, df) rmse(model = mod, data = df))
  )

# Combine metrics for all models
summary_results=cv_results |&gt; 
  summarise(

    mean_rmse_model1 = mean(rmse_model1),
    mean_rmse_model2 = mean(rmse_model2)
  )

print(summary_results)</code></pre>
<pre><code>## # A tibble: 1 × 2
##   mean_rmse_model1 mean_rmse_model2
##              &lt;dbl&gt;            &lt;dbl&gt;
## 1            0.718             1.14</code></pre>
<pre class="r"><code>cv_long=cv_results |&gt; select(starts_with(&quot;rmse&quot;))|&gt;
  pivot_longer(
    everything(),
    names_to = &quot;model&quot;, 
    values_to = &quot;rmse&quot;,
    names_prefix = &quot;rmse_&quot;) |&gt; 
  mutate(model = fct_inorder(model))


cv_long|&gt;ggplot(aes(x = model, y = rmse)) + 
   geom_violin()+
  labs(
    title = &quot;Cross-Validated RMSE for fatality&quot;,
    x = &quot;Model&quot;,
    y = &quot;RMSE&quot;
  ) +
  theme_minimal()</code></pre>
<p><img src="model_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
<p>It is observed that the better performance of the first model
<code>model1_mod</code> using cross-validation is slightly better
compared to the second model <code>model2_mod</code>, with the RMSE
increase from about 0.71 to 1.12.</p>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
